/**
 * @file    stm32f1xx_hal_i2c.h
 * @brief   STM32 HAL I2C stub header
 *
 * @details Provides I2C types and function declarations so firmware
 *          referencing I2C compiles cleanly in CI during Sprint 2-4,
 *          before the real CubeMX HAL is added in Sprint 5.
 *
 *          Sprint 5 action: Replace with real stm32f1xx_hal_i2c.h
 *          generated by STM32CubeMX after configuring I2C1.
 *
 * @author  BaseSync Team
 * @version 1.0 (Sprint 2 stub)
 */

#ifndef STM32F1XX_HAL_I2C_H
#define STM32F1XX_HAL_I2C_H

#include <stdint.h>
#include "stm32f1xx_hal.h"

/* ─── I2C Handle ─────────────────────────────────────────────────────────── */
typedef struct
{
    uint32_t Instance;      /**< I2C peripheral base address   */
    uint32_t ClockSpeed;    /**< SCL clock speed in Hz         */
    uint32_t State;         /**< I2C state flags               */
    uint32_t ErrorCode;     /**< Last error code               */
} I2C_HandleTypeDef;

/* ─── Peripheral base addresses ──────────────────────────────────────────── */
#define I2C1  ((uint32_t)0x40005400U)
#define I2C2  ((uint32_t)0x40005800U)

/* ─── Memory address size defines ────────────────────────────────────────── */
#define I2C_MEMADD_SIZE_8BIT    (0x00000001U)
#define I2C_MEMADD_SIZE_16BIT   (0x00000002U)

/* ─── I2C function declarations ──────────────────────────────────────────── */

/**
 * @brief Send data to an I2C slave device.
 * @param hi2c       I2C handle pointer
 * @param DevAddress 8-bit device address (7-bit addr shifted left by 1)
 * @param pData      Pointer to data buffer
 * @param Size       Number of bytes to send
 * @param Timeout    Timeout in milliseconds
 */
HAL_StatusTypeDef HAL_I2C_Master_Transmit(I2C_HandleTypeDef *hi2c,
                                            uint16_t           DevAddress,
                                            uint8_t           *pData,
                                            uint16_t           Size,
                                            uint32_t           Timeout);

/**
 * @brief Receive data from an I2C slave device.
 */
HAL_StatusTypeDef HAL_I2C_Master_Receive(I2C_HandleTypeDef *hi2c,
                                           uint16_t           DevAddress,
                                           uint8_t           *pData,
                                           uint16_t           Size,
                                           uint32_t           Timeout);

/**
 * @brief Write to a specific register inside an I2C device.
 *
 * @details Sends: [DevAddress W] [MemAddress] [data bytes...]
 *          Used for: TMP102 configuration register writes in Sprint 5.
 *
 * @param MemAddress    Register address inside the device
 * @param MemAddSize    I2C_MEMADD_SIZE_8BIT or I2C_MEMADD_SIZE_16BIT
 */
HAL_StatusTypeDef HAL_I2C_Mem_Write(I2C_HandleTypeDef *hi2c,
                                      uint16_t           DevAddress,
                                      uint16_t           MemAddress,
                                      uint16_t           MemAddSize,
                                      uint8_t           *pData,
                                      uint16_t           Size,
                                      uint32_t           Timeout);

/**
 * @brief Read from a specific register inside an I2C device.
 *
 * @details Sends: [DevAddress W] [MemAddress] repeated-start [DevAddress R] [data...]
 *          Used for: TMP102 temperature register reads in Sprint 5.
 */
HAL_StatusTypeDef HAL_I2C_Mem_Read(I2C_HandleTypeDef *hi2c,
                                     uint16_t           DevAddress,
                                     uint16_t           MemAddress,
                                     uint16_t           MemAddSize,
                                     uint8_t           *pData,
                                     uint16_t           Size,
                                     uint32_t           Timeout);

/**
 * @brief Check if an I2C device responds at the given address.
 *
 * @details Sends a start condition and the device address, then checks
 *          for ACK. Returns HAL_OK if device responds. Used in Sprint 5
 *          to verify TMP102 is wired correctly before enabling I2C reads.
 *
 * @param Trials  Number of retry attempts
 */
HAL_StatusTypeDef HAL_I2C_IsDeviceReady(I2C_HandleTypeDef *hi2c,
                                          uint16_t           DevAddress,
                                          uint32_t           Trials,
                                          uint32_t           Timeout);

#endif /* STM32F1XX_HAL_I2C_H */
