/**
 * @file    stm32f1xx_hal.h
 * @brief   STM32F1xx HAL stub header for compilation without full CubeMX setup
 *
 * @details This is a STUB (fake/minimal) version of the STM32 HAL header.
 *          It defines only the types and return codes needed to compile
 *          our firmware source files during development and CI.
 *
 *          In Sprint 5 (Hardware Bring-Up), this will be REPLACED with the
 *          real STM32 HAL generated by STM32CubeMX.
 *
 *          Why do we need this?
 *          Our sensor_hal.c and motor_ctrl.c call functions like
 *          HAL_ADC_Start(), HAL_GPIO_ReadPin(), etc. The compiler needs
 *          to find these declarations. The full HAL is 200+ files from ST
 *          — for now, we stub the minimal types needed.
 *
 * @warning Do NOT use in production firmware. Replace with real HAL.
 *
 * @author  BaseSync Team
 * @version 1.0
 * @date    2025
 */

#ifndef STM32F1XX_HAL_H
#define STM32F1XX_HAL_H

/* ─── Standard library types ─────────────────────────────────────────────── */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ─── HAL Status codes ────────────────────────────────────────────────────── */
/**
 * @brief HAL function return status.
 * Mirrors the real HAL_StatusTypeDef exactly.
 */
typedef enum
{
    HAL_OK      = 0x00U,  /**< Operation successful */
    HAL_ERROR   = 0x01U,  /**< Operation failed     */
    HAL_BUSY    = 0x02U,  /**< Peripheral busy      */
    HAL_TIMEOUT = 0x03U   /**< Operation timed out  */
} HAL_StatusTypeDef;

/* ─── Common types ────────────────────────────────────────────────────────── */
typedef uint32_t HAL_TickType;

/* ─── Include peripheral-specific stubs ──────────────────────────────────── */
#include "stm32f1xx_hal_gpio.h"
#include "stm32f1xx_hal_adc.h"
#include "stm32f1xx_hal_tim.h"

/* Sprint 5 preparation: UART and I2C stubs */
#include "stm32f1xx_hal_uart.h"
#include "stm32f1xx_hal_i2c.h"

/* Sprint 6 preparation: SPI stub */
#include "stm32f1xx_hal_spi.h"

/* ─── HAL core function stubs ────────────────────────────────────────────── */
/* These are declared here and will be provided by either:
 * - Real HAL in Sprint 5+
 * - Mock functions in unit tests (Tests/mocks/)
 */

/**
 * @brief Returns the current system tick in milliseconds.
 * Real implementation uses SysTick. Mock returns a controllable value.
 */
uint32_t HAL_GetTick(void);

/**
 * @brief Delays execution for the given number of milliseconds.
 */
void HAL_Delay(uint32_t delay_ms);

#endif /* STM32F1XX_HAL_H */
