/**
 * @file    stm32f1xx_hal_spi.h
 * @brief   STM32 HAL SPI stub header
 *
 * @details Provides SPI types and function declarations so firmware
 *          referencing SPI compiles cleanly in CI during Sprint 2-5,
 *          before the real CubeMX HAL is added in Sprint 6.
 *
 *          Sprint 6 action: Replace with real stm32f1xx_hal_spi.h
 *          generated by STM32CubeMX after configuring SPI1.
 *
 * @author  BaseSync Team
 * @version 1.0 (Sprint 2 stub)
 */

#ifndef STM32F1XX_HAL_SPI_H
#define STM32F1XX_HAL_SPI_H

#include <stdint.h>
#include "stm32f1xx_hal.h"

/* ─── SPI Handle ─────────────────────────────────────────────────────────── */
typedef struct
{
    uint32_t Instance;            /**< SPI peripheral base address          */
    uint32_t BaudRatePrescaler;   /**< Clock prescaler (APB clock / n)      */
    uint32_t CLKPolarity;         /**< CPOL: clock idle state               */
    uint32_t CLKPhase;            /**< CPHA: data capture edge              */
    uint32_t State;               /**< SPI state flags                      */
    uint32_t ErrorCode;           /**< Last error code                      */
} SPI_HandleTypeDef;

/* ─── Peripheral base addresses ──────────────────────────────────────────── */
#define SPI1  ((uint32_t)0x40013000U)
#define SPI2  ((uint32_t)0x40003800U)

/* ─── SPI function declarations ──────────────────────────────────────────── */

/**
 * @brief Transmit data over SPI in blocking mode.
 *
 * @details CS (chip select) must be asserted by the caller BEFORE this call
 *          and deasserted AFTER. The HAL does not manage CS automatically.
 *
 *          Usage example (Sprint 6):
 *          @code
 *            HAL_GPIO_WritePin(EV_SPI_FLASH_CS_PORT, EV_SPI_FLASH_CS_PIN,
 *                              GPIO_PIN_RESET);           // CS LOW
 *            HAL_SPI_Transmit(&hspi1, cmd, 1, timeout);
 *            HAL_GPIO_WritePin(EV_SPI_FLASH_CS_PORT, EV_SPI_FLASH_CS_PIN,
 *                              GPIO_PIN_SET);             // CS HIGH
 *          @endcode
 *
 * @param hspi     SPI handle pointer
 * @param pData    Pointer to data to transmit
 * @param Size     Number of bytes
 * @param Timeout  Timeout in milliseconds
 */
HAL_StatusTypeDef HAL_SPI_Transmit(SPI_HandleTypeDef *hspi,
                                    const uint8_t     *pData,
                                    uint16_t           Size,
                                    uint32_t           Timeout);

/**
 * @brief Receive data over SPI in blocking mode.
 * Transmits dummy bytes (0xFF) on MOSI while reading MISO.
 */
HAL_StatusTypeDef HAL_SPI_Receive(SPI_HandleTypeDef *hspi,
                                   uint8_t           *pData,
                                   uint16_t           Size,
                                   uint32_t           Timeout);

/**
 * @brief Simultaneously transmit and receive data (full-duplex).
 *
 * @details Used for SPI flash operations where a command is sent and
 *          the response arrives on MISO in the same transaction:
 *          e.g., READ_JEDEC_ID sends 0x9F and receives 3 ID bytes.
 *
 * @param pTxData  Data to transmit (command bytes)
 * @param pRxData  Buffer to store received data
 */
HAL_StatusTypeDef HAL_SPI_TransmitReceive(SPI_HandleTypeDef *hspi,
                                           const uint8_t     *pTxData,
                                           uint8_t           *pRxData,
                                           uint16_t           Size,
                                           uint32_t           Timeout);

#endif /* STM32F1XX_HAL_SPI_H */
