/**
 * @file    stm32f1xx_hal_uart.h
 * @brief   STM32 HAL UART stub header
 *
 * @details Provides UART types and function declarations so firmware
 *          code referencing UART can compile cleanly in CI during
 *          Sprint 2-4, before real CubeMX HAL is added in Sprint 5.
 *
 *          Sprint 5 action: Replace this file with the real
 *          stm32f1xx_hal_uart.h generated by STM32CubeMX.
 *
 * @author  BaseSync Team
 * @version 1.0 (Sprint 2 stub)
 */

#ifndef STM32F1XX_HAL_UART_H
#define STM32F1XX_HAL_UART_H

#include <stdint.h>
#include "stm32f1xx_hal.h"

/* ─── UART Handle ─────────────────────────────────────────────────────────── */
typedef struct
{
    uint32_t Instance;    /**< UART peripheral base address  */
    uint32_t BaudRate;    /**< Configured baud rate          */
    uint32_t State;       /**< UART state flags              */
} UART_HandleTypeDef;

/* ─── Peripheral base addresses ──────────────────────────────────────────── */
#define USART1   ((uint32_t)0x40013800U)
#define USART2   ((uint32_t)0x40004400U)
#define USART3   ((uint32_t)0x40004800U)

/* ─── UART function declarations ─────────────────────────────────────────── */

/**
 * @brief Transmit data over UART in blocking mode.
 * @param huart    UART handle pointer
 * @param pData    Pointer to data buffer to transmit
 * @param Size     Number of bytes to transmit
 * @param Timeout  Timeout in milliseconds
 */
HAL_StatusTypeDef HAL_UART_Transmit(UART_HandleTypeDef *huart,
                                     const uint8_t      *pData,
                                     uint16_t            Size,
                                     uint32_t            Timeout);

/**
 * @brief Receive data over UART in blocking mode.
 */
HAL_StatusTypeDef HAL_UART_Receive(UART_HandleTypeDef *huart,
                                    uint8_t            *pData,
                                    uint16_t            Size,
                                    uint32_t            Timeout);

/**
 * @brief Transmit data over UART using DMA (non-blocking).
 * Sprint 5+: use for high-throughput logging without blocking the main loop.
 */
HAL_StatusTypeDef HAL_UART_Transmit_DMA(UART_HandleTypeDef *huart,
                                          const uint8_t      *pData,
                                          uint16_t            Size);

#endif /* STM32F1XX_HAL_UART_H */
